resources:
  - bot.yaml
  - web-shim.yaml
  - web-shim-service.yaml
  - web-shim-ingress.yaml

images:
  - name: vatusa/discord-bot-v3
    newTag: "1.0.29"
  - name: vatusa/discord-bot-v3-web-shim
    newTag: "1.0.29"